require 'rbconfig'

namespace :zkrb do
  task :clean do
    if File.exists?('Makefile')
      sh 'make clean'
      rm 'Makefile' # yep, regenerate this
    else
      $stderr.puts "nothing to clean, no Makefile"
    end
  end

  task :clobber => :clean do
    rm_rf %w[Makefile c lib bin include ._c]
  end
end

task :clean   => 'zkrb:clean'
task :clobber => 'zkrb:clobber'

GENERATE_GVL_CODE_RB = 'generate_gvl_code.rb'

file 'zkrb_wrapper.c' => GENERATE_GVL_CODE_RB do
  sh "ruby generate_gvl_code.rb code"
end

file 'zkrb_wrapper.h' => GENERATE_GVL_CODE_RB do
  sh "ruby generate_gvl_code.rb headers"
end

ZKRB_WRAPPER = %w[zkrb_wrapper.c zkrb_wrapper.h]

task :wrappers => ZKRB_WRAPPER

file 'Makefile' do
  sh "ruby extconf.rb"
end

task :build => [ZKRB_WRAPPER, 'Makefile'].flatten do
  sh 'make'
end

task :default => :build

