AZK_ROOT  = 'apache-zookeeper'
AZK_SRC   = File.join(AZK_ROOT, 'src')
AZK_C_SRC = File.join(AZK_SRC, 'c')

GENERATED_DIR = File.join(AZK_C_SRC, 'generated')

CONFIGURE_PATH = File.join(AZK_C_SRC, 'configure')

file GENERATED_DIR do
  cd AZK_C_SRC do
    sh 'ant compile_jute'
  end
end

file CONFIGURE_PATH => GENERATED_DIR do
  cd AZK_C_SRC do
    sh 'autoreconf -if'
  end
end


task :clean do
  if File.exists?('Makefile')
    sh 'make clean'
  else
    $stderr.puts "nothing to clean, no Makefile"
  end
end

GENERATE_GVL_CODE_RB = 'generate_gvl_code.rb'

# file 'c' do
#   if tarball = Dir['zkc-*.tar.gz'].first
#     sh "tar -zxf #{tarball}"
#   else
#     raise "couldn't find the tarball! wtf?!"
#   end
# end

file GENERATE_GVL_CODE_RB 

file 'zkrb_wrapper.c' => GENERATE_GVL_CODE_RB do
  sh "ruby generate_gvl_code.rb code"
end

file 'zkrb_wrapper.h' => GENERATE_GVL_CODE_RB do
  sh "ruby generate_gvl_code.rb headers"
end

ZKRB_WRAPPER = %w[zkrb_wrapper.c zkrb_wrapper.h]


task :wrappers => ZKRB_WRAPPER

task :clobber => :clean do
  rm_rf %w[Makefile c lib bin include]
end

task :build_zkc => CONFIGURE_PATH do
  sh 'ruby extconf.rb'
end

file 'Makefile' => :build_zkc

task :build => [ZKRB_WRAPPER, 'Makefile'].flatten do
  sh 'make'
end

task :default => :build

