on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} / GCC ${{ matrix.gcc }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - jruby
        gcc:
          - 7
          - latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.gcc }}
          platform: x64

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run Tests
        env:
          RAILS_ENV: test
          SPAWN_ZOOKEEPER: true
        run: |
          bundle exec rake
